### ISSUE TITLE
Can't seem to plot a parametric  region

### ISSUE THREAD

**Issue by Riccardo-Sironi** [MarcosNicolau/obsidian-mathematica-plot#6]
Whenever I try to plot a parametric region, using an additional variable (v), the graphing stops working. 

I tried plotting the example from Wolfram's Docs - https://wolfram.com/xid/0i1m5ycpu-srn

```mathematica-plot 
raster:
  dim: 2D
  background: White
  size:
    height: Automatic
    width: "250"
general:
  axes: "True"
  axesLabel: "{x, y}"
  frame: "False"
  boxed: "True"
graphs:
  - id: graph_0
    options: {}
    type: parametricPlot
    parametricPlot:
      components:
        - v^2 (Sqrt[u] Cos[u])
        - v^2(Sin[u])
      type: curve
      domain:
        u:
          min: "0"
          max: 3 Pi / 2
        v:
          min: "1"
          max: "2"

 ```

**Comment by MarcosNicolau** [comment]
Hi @Riccardo-Sironi, you might have already solved this, but the problem lies in the dimension. If you want to have two components in the domain, then change the dim to 3D.

I know it may be confusing that it generates a `v` component in the final yml. I'll make sure to change that in a future release.

**Comment by Riccardo-Sironi** [comment]
Oh, got it. Thank you very much
